workflows:
  unity-ios:
    environment:
      xcode: latest
      cocoapods: default
      unity: 6000.0.56f1
      ios_signing:
        # Явно указываем, какие сертификаты/профили ставить
        certificates:
          - apple_distribution           # <- reference name сертификата из UI
        provisioning_profiles:
          - merspace_appstore           # <- reference name профиля app
          - merspace_nse_appstore       # <- reference name профиля NSE
      groups:
        - unity_credentials
        - app_store_credentials
      vars:
        BUNDLE_ID: com.joams.merspace
        NSE_BUNDLE_ID: com.joams.merspace.OneSignalNotificationServiceExtension
        APP_STORE_APPLE_ID: 6751573211
        UNITY_IOS_DIR: ios
        XCODE_WORKSPACE: Unity-iPhone.xcworkspace
        XCODE_SCHEME: Unity-iPhone

    scripts:
      - name: Activate Unity license
        script: |
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile \
            -serial "${UNITY_SERIAL}" -username "${UNITY_EMAIL}" -password "${UNITY_PASSWORD}"

      - name: Export iOS project from Unity
        script: |
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile \
            -projectPath . -executeMethod BuildScript.BuildIos -nographics

      - name: Install CocoaPods
        script: |
          cd "$UNITY_IOS_DIR"
          pod install

      - name: Set up keychain & install identities from team storage
        script: |
          keychain initialize
          keychain add-certificates        # <-- установит сертификаты и профили, которые ты задал в ios_signing

      - name: Apply provisioning profiles to Xcode project
        script: xcode-project use-profiles

      - name: Increment build number
        script: |
          LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" || app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID" || echo 0)
          cd "$UNITY_IOS_DIR"
          agvtool new-version -all $((LATEST + 1))

      - name: Build IPA
        script: |
          xcode-project build-ipa --workspace "$UNITY_IOS_DIR/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"


    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

      scripts:
        - name: Deactivate Unity license
          script: |
            /Applications/Unity\ Hub.app/Contents/Frameworks/UnityLicensingClient_V1.app/Contents/MacOS/Unity.Licensing.Client \
              --return-ulf \
              --username "${UNITY_EMAIL}" \
              --password "${UNITY_PASSWORD}" \
              || $UNITY_HOME/Contents/MacOS/Unity -quit -batchmode -returnlicense || true
