workflows:
  unity-ios:
    name: Unity iOS (6000.1.5f1 via Hub)
    environment:
      # Важно: НЕ указываем environment.unity для 6000.1.5f1 — ставим через Hub CLI.
      groups:
        - unity_credentials            # UNITY_EMAIL / UNITY_PASSWORD / UNITY_SERIAL
        - app_store_credentials        # APP_STORE_CONNECT_ISSUER_ID / KEY_IDENTIFIER / PRIVATE_KEY (.p8)
        - certificate_credentials      # CERTIFICATE_PRIVATE_KEY = PEM RSA (BEGIN RSA PRIVATE KEY)
      vars:
        UNITY_VERSION: "6000.1.5f1"
        UNITY_CHANGESET: "923722cbbcfc"
        IOS_EXPORT_PATH: "build/ios"
        XCODE_WORKSPACE: "Unity-iPhone.xcworkspace"
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
        BUNDLE_ID: "com.joams.merspace"
        NSE_BUNDLE_ID: "com.joams.merspace.OneSignalNotificationServiceExtension"
        APP_STORE_APPLE_ID: "6751573211"
      xcode: latest
      cocoapods: default

    scripts:
      # 0) Поставим Unity 6000.1.5f1 + iOS модуль через Unity Hub CLI
      - name: Install Unity via Hub CLI
        script: |
          set -e
          HUB="/Applications/Unity Hub.app/Contents/MacOS/Unity Hub"
          # Editor
          yes Y | "$HUB" -- --headless install --version "$UNITY_VERSION" --changeset "$UNITY_CHANGESET" -a arm64
          # iOS Build Support
          yes Y | "$HUB" -- --headless install-modules --version "$UNITY_VERSION" -m ios -a arm64
          # Укажем установленную версию как активную для следующих шагов
          echo "UNITY_HOME=/Applications/Unity/Hub/Editor/${UNITY_VERSION}/Unity.app" >> $CM_ENV
          "$UNITY_HOME/Contents/MacOS/Unity" -version

      # 1) Активируем лицензию (Edu Pro)
      - name: Activate Unity license
        script: |
          "$UNITY_HOME/Contents/MacOS/Unity" -batchmode -quit -logFile \
            -serial "${UNITY_SERIAL}" \
            -username "${UNITY_EMAIL}" \
            -password "${UNITY_PASSWORD}"

      # 2) Экспорт iOS-проекта из Unity (метод BuildScript.BuildiOS в Assets/Editor/Build.cs)
      - name: Export iOS project
        script: |
          "$UNITY_HOME/Contents/MacOS/Unity" \
            -batchmode -nographics -quit -logFile \
            -projectPath "$(pwd)" \
            -executeMethod BuildScript.BuildiOS
          echo "Exported to: $IOS_EXPORT_PATH"

      # 3) CocoaPods (OneSignal подтянется из Podfile, который создаёт EDM4U → iOS Resolver)
      - name: Install CocoaPods
        script: |
          cd "$IOS_EXPORT_PATH"
          pod repo update || true
          pod install

      # 4) Коды-подписи: ключница + профили для App и NSE (автогенерация)
      - name: Setup signing (keychain & provisioning profiles)
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID"     --type IOS_APP_STORE --platform=IOS --create --certificate-key @env:CERTIFICATE_PRIVATE_KEY
          app-store-connect fetch-signing-files "$NSE_BUNDLE_ID" --type IOS_APP_STORE --platform=IOS --create --certificate-key @env:CERTIFICATE_PRIVATE_KEY
          keychain add-certificates

      # 5) Привязать профили к Xcode-проекту
      - name: Apply provisioning profiles
        script: |
          cd "$IOS_EXPORT_PATH"
          xcode-project use-profiles

      # 6) Инкремент номера билда по TestFlight
      - name: Increment build number
        script: |
          LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" || echo 0)
          cd "$IOS_EXPORT_PATH"
          agvtool new-version -all $((LATEST + 1))

      # 7) Сборка IPA
      - name: Build IPA
        script: |
          cd "$IOS_EXPORT_PATH"
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

    publishing:
      # 8) Возврат лицензии Unity
      scripts:
        - name: Deactivate Unity license
          script: |
            "$UNITY_HOME/Contents/MacOS/Unity" -batchmode -quit -returnlicense -nographics
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

    artifacts:
      - $IOS_EXPORT_PATH/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
