workflows:
  unity-ios:
    name: Unity iOS (Merspace)
    environment:
      unity: "6000.1.5f1"   # <-- твоя версия Unity
      groups:
        - unity_credentials           # UNITY_EMAIL / UNITY_PASSWORD / UNITY_SERIAL
        - app_store_credentials       # APP_STORE_CONNECT_ISSUER_ID / KEY_IDENTIFIER / PRIVATE_KEY (.p8)
        - certificate_credentials     # CERTIFICATE_PRIVATE_KEY = PEM RSA (BEGIN RSA PRIVATE KEY)
      vars:
        IOS_EXPORT_PATH: "build/ios"
        XCODE_WORKSPACE: "Unity-iPhone.xcworkspace"
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
        BUNDLE_ID: "com.joams.merspace"
        NSE_BUNDLE_ID: "com.joams.merspace.OneSignalNotificationServiceExtension"
        APP_STORE_APPLE_ID: "6751573211"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Activate Unity license
        script: |
          "$UNITY_HOME/Contents/MacOS/Unity" -batchmode -quit -logFile \
            -serial "${UNITY_SERIAL}" \
            -username "${UNITY_EMAIL}" \
            -password "${UNITY_PASSWORD}"

      - name: Export iOS project from Unity
        script: |
          "$UNITY_HOME/Contents/MacOS/Unity" \
            -batchmode -nographics -quit -logFile \
            -projectPath "$(pwd)" \
            -executeMethod BuildScript.BuildiOS
          echo "Exported to: $IOS_EXPORT_PATH"

      - name: Install CocoaPods
        script: |
          cd "$IOS_EXPORT_PATH"
          pod repo update || true
          pod install

      - name: Setup signing (keychain & provisioning profiles)
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID"     --type IOS_APP_STORE --platform=IOS --create --certificate-key @env:CERTIFICATE_PRIVATE_KEY
          app-store-connect fetch-signing-files "$NSE_BUNDLE_ID" --type IOS_APP_STORE --platform=IOS --create --certificate-key @env:CERTIFICATE_PRIVATE_KEY
          keychain add-certificates

      - name: Apply provisioning profiles to Xcode project
        script: |
          cd "$IOS_EXPORT_PATH"
          xcode-project use-profiles

      - name: Increment build number (TestFlight)
        script: |
          LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" || echo 0)
          cd "$IOS_EXPORT_PATH"
          agvtool new-version -all $((LATEST + 1))

      - name: Build IPA
        script: |
          cd "$IOS_EXPORT_PATH"
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

    publishing:
      scripts:
        - name: Deactivate Unity license
          script: |
            "$UNITY_HOME/Contents/MacOS/Unity" -batchmode -quit -returnlicense -nographics
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

    artifacts:
      - $IOS_EXPORT_PATH/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
