workflows:
  unity-ios:
    name: Unity iOS (Merspace + OneSignal)
    max_build_duration: 120
    environment:
      groups:
        - app_store_credentials         # APP_STORE_CONNECT_PRIVATE_KEY, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_ISSUER_ID
        - unity_credentials             # UNITY_EMAIL, UNITY_PASSWORD, UNITY_SERIAL
        - certificate_credentials       # CERTIFICATE_PASSWORD  (пароль для .p12)
      vars:
        UNITY_VERSION: "6000.0.56f1"
        UNITY_HOME: "/Applications/Unity/Hub/Editor/6000.0.56f1/Unity.app"

        # Пути/идентификаторы проекта
        IOS_EXPORT_PATH: "build/ios"
        BUNDLE_ID: "com.joams.merspace"
        NSE_BUNDLE_ID: "com.joams.merspace.OneSignalNotificationServiceExtension"
        APP_GROUP: "group.com.joams.merspace"

        # Числовой Apple ID приложения (для авто-инкремента билда)
        APP_STORE_APPLE_ID: "6751573211"

      xcode: latest
      cocoapods: default

    scripts:
      - name: Show Unity info
        script: |
          "$UNITY_HOME/Contents/MacOS/Unity" -version
          echo "UNITY_HOME=$UNITY_HOME"

      - name: Activate Unity (serial)
        script: |
          "$UNITY_HOME/Contents/MacOS/Unity" \
            -batchmode -nographics -quit -logFile - \
            -serial "$UNITY_SERIAL" \
            -username "$UNITY_EMAIL" \
            -password "$UNITY_PASSWORD"

      - name: Check BuildScript
        script: |
          set -e
          test -f "Assets/Editor/BuildScript.cs" || { echo "Missing Assets/Editor/BuildScript.cs"; exit 1; }
          grep -qi "BuildScript.BuildiOS" Assets/Editor/BuildScript.cs || { echo "BuildScript.BuildiOS not found"; exit 1; }

      - name: Export iOS project from Unity
        script: |
          set -e
          "$UNITY_HOME/Contents/MacOS/Unity" \
            -batchmode -nographics -quit -logFile - \
            -projectPath "$(pwd)" \
            -executeMethod BuildScript.BuildiOS
          echo "Exported to: $IOS_EXPORT_PATH"
          ls -la "$IOS_EXPORT_PATH" || true

      - name: Install CocoaPods in export
        script: |
          set -e
          cd "$IOS_EXPORT_PATH"
          if [ -f "Podfile" ]; then
            pod repo update || true
            pod install
          else
            echo "No Podfile found. Did you run EDM4U resolver before export?" && exit 1
          fi

      # ВАЖНО: создаём/скачиваем сертификаты и профили под оба Bundle ID
      - name: Fetch signing files (App + NSE)
        script: |
          set -e
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE --platform IOS --create \
            --certificate-key-password "$CERTIFICATE_PASSWORD"
          app-store-connect fetch-signing-files "$NSE_BUNDLE_ID" \
            --type IOS_APP_STORE --platform IOS --create \
            --certificate-key-password "$CERTIFICATE_PASSWORD"

          echo "Downloaded certs:"; ls -la "$HOME/Library/MobileDevice/Certificates" || true
          echo "Downloaded profiles:"; ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true

      - name: Import Apple certificates
        script: keychain add-certificates

      - name: Apply provisioning & entitlements
        script: |
          set -e
          cd "$IOS_EXPORT_PATH"
          xcode-project use-profiles

          # гарантируем App Group в энтайтламентах App + NSE
          for ENT in \
            "Unity-iPhone/Unity-iPhone.entitlements" \
            "OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension.entitlements"
          do
            if [ ! -f "$ENT" ]; then
              mkdir -p "$(dirname "$ENT")"
              /usr/libexec/PlistBuddy -c "Save" "$ENT" 2>/dev/null || true
              touch "$ENT"
            fi
            /usr/libexec/PlistBuddy -c "Add :com.apple.security.application-groups array" "$ENT" 2>/dev/null || true
            /usr/libexec/PlistBuddy -c "Delete :com.apple.security.application-groups:0" "$ENT" 2>/dev/null || true
            /usr/libexec/PlistBuddy -c "Add :com.apple.security.application-groups:0 string $APP_GROUP" "$ENT"
            /usr/libexec/PlistBuddy -c "Print :com.apple.security.application-groups" "$ENT" || true
          done

      - name: Increment build number
        script: |
          LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" || echo 0)
          cd "$IOS_EXPORT_PATH"
          agvtool new-version -all $((LATEST + 1))

      - name: Build ipa
        script: |
          set -e
          cd "$IOS_EXPORT_PATH"
          if [ -d "Unity-iPhone.xcworkspace" ]; then
            xcode-project build-ipa --workspace "Unity-iPhone.xcworkspace" --scheme "Unity-iPhone"
          else
            xcode-project build-ipa --project "Unity-iPhone.xcodeproj" --scheme "Unity-iPhone"
          fi

    artifacts:
      - $IOS_EXPORT_PATH/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

    after_scripts:
      - name: Deactivate Unity
        script: |
          "$UNITY_HOME/Contents/MacOS/Unity" -batchmode -quit -returnlicense -nographics || true
